apiVersion : apps/v1
kind: Deployment
metadata:
  name: "eshopcoffe-prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshopcoffe-prod
  template:
    metadata:
      labels:
        app: eshopcoffe-prod
    spec:
      containers:
        - name: eshopcoffe-prod
          image: "abreuzooka/eshopcoffe:latest"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80