apiVersion : apps/v1
kind: Deployment
metadata:
  name: "eshopcoffe-15a9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "eshopcoffe-15a9"
  template:
    metadata:
      labels:
        app: "eshopcoffe-15a9"
    spec:
      containers:
        - name: "eshopcoffe-15a9"
          image: "eshopcoffe.azurecr.io/eshopcoffe"
          ports:
          - containerPort: 80