name: Backend - Build & Push

on: workflow_dispatch

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: abreuzooka/eshopcoffe:latest, abreuzooka/eshopcoffe:${{ github.run_number }}
          build-args: |
            DATABASE_SERVER=${{ secrets.DATABASE_SERVER }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES=${{ secrets.JWT_EXPIRES }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}